### ISSUE TITLE
SAML-LAB suggestions

### ISSUE THREAD

**Issue by arloparanhos** [geordielad/gsko2019#6]
change 
"Check enable an additional authentication option under Authentication types" to
"Under Authentication types, Check 'Enable an additional authentication method'.  Then, under SAML, click 'Edit Connection...'

for step 2, add URL and explanation.  This link goes straight to classic UI, so may not need the classicUI redirect later.  
"https://dev-xxxxxx-admin.oktapreview.com/admin/dashboard where xxxxxx is your personal dev console (sent by Okta)."
"Click 'Add Applications'
Search for 'Tableau'.  Select Table

**Comment by geordielad** [comment]
'Check enable fixed - thanjks.

I am not sure under what circumstances Classic UI comes up v Developer bu I will add the link.
